version: '3.8'
services:
  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: fossil
      POSTGRES_USER: fossil
      POSTGRES_PASSWORD: fossil
    volumes:
      - ./devops/local/pg-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
