version: '3'
services:
  postgres:
    image: postgres:10.9
    environment:
      - POSTGRES_USER=fossil
      - POSTGRES_DB=fossil
      - POSTGRES_PASSWORD=fossil
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pghero:
    image: ankane/pghero
    environment:
    - DATABASE_URL=postgres://fossil:fossil@postgres:5432/fossil
    ports:
    - "8081:8080"
    depends_on:
    - postgres

  fossil:
    image: sroze/fossil:latest
    environment:
    - SERVER_PORT=80
    - DATABASE_URL=postgres://fossil:fossil@postgres/fossil
    - LOGGING_LEVEL=info
    depends_on:
      - postgres
    ports:
    - "8080:80"

  influxdb:
    build: influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUX_DB=gatlingdb
    ports:
      - "2003:2003"
      - "8086:8086"

  grafana:
    build: grafana
    environment:
      #- GF_SECURITY_ADMIN_USER=admin
      #- GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel
    volumes:
      - /var/lib/grafana
    links:
      - influxdb
    ports:
      - '3000:3000'

  gatling:
    image: denvazh/gatling:3.2.1
    volumes:
      - ./gatling/conf:/opt/gatling/conf
      - ./results:/opt/gatling/results
      - ./:/opt/gatling/user-files/simulations
    depends_on:
      - fossil
    links:
      - influxdb
    environment:
      - FOSSIL_URL=http://fossil

  cadvisor:
    image: google/cadvisor
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    links:
      - influxdb

  telegraf:
    image: telegraf:1.12
    depends_on:
      - influxdb
      - postgres
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
