name: Birdie API CICD
on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      localstack:
        image: localstack/localstack
        env:
          HOSTNAME: localstack
          HOSTNAME_EXTERNAL: localstack
        ports:
          - 4566:4566
        options: --health-cmd "curl -f http://localhost:4566/health || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      # apps/api
      API_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      # apps/website
      WEBSITE_DATABASE_URL: postgres://postgres:postgres@localhost:5432/website
      # libs/*
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - uses: pnpm/action-setup@v2
        with:
          version: 7.30.5

      - name: NPM Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('pnpm-lock.yaml') }}-v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Database setup
        run: psql $API_DATABASE_URL < ./devops/local/pg-init.sql

      - name: Run tests
        run: pnpm test
